blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/sys-hackathon/Recall-Analysis-WebApp/discussions
    about: Please ask and answer questions here.

issue_template:
  - name: Bug Report
    description: File a bug report
    title: "[BUG] - "
    labels: ["bug", "needs triage"]
    body:
      - type: markdown
        attributes:
          value: |
            Thanks for taking the time to fill out this bug report!
      - type: input
        id: version
        attributes:
          label: Version
          description: What version of our software are you running?
          placeholder: e.g. v1.0.0
        validations:
          required: true
      - type: textarea
        id: what-happened
        attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
        validations:
          required: true
      - type: dropdown
        id: browsers
        attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
            - Firefox
            - Chrome
            - Safari
            - Microsoft Edge
      - type: textarea
        id: logs
        attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell

  - name: Feature Request
    description: Suggest an idea for this project
    title: "[FEATURE] - "
    labels: ["enhancement", "needs triage"]
    body:
      - type: markdown
        attributes:
          value: |
            Thanks for taking the time to fill out this feature request!
      - type: textarea
        id: feature-description
        attributes:
          label: Describe the feature you'd like
          description: A clear and concise description of what you want to happen.
        validations:
          required: true
      - type: textarea
        id: additional-context
        attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.

  - name: Onboarding Developer Tasks
    description: Template for onboarding new developers to the Recall Analysis WebApp project.
    title: "[Onboarding] New Developer Tasks"
    labels: ["onboarding"]
    body:
      - type: markdown
        attributes:
          value: |
            This issue is for new developers to complete the onboarding process for the **Recall Analysis WebApp** project. Please follow the steps below to get started:
      - type: textarea
        id: step-1
        attributes:
          label: Step 1: Clone Repository and Start Development
          description: |
            - **Objective:** Clone the repository to your local machine and start development work.

            **Steps:**

            1. **Clone the Repository:**
               ```
               git clone git@github.com:sys-hackathon/Recall-Analysis-WebApp.git
               cd Recall-Analysis-WebApp
               ```

            2. **Set Up Development Environment:**
               - Install dependencies:
                 ```
                 npm install
                 ```
               - Set up your SQL database with the necessary tables for recall data.

            3. **Start Development:**
               - Begin implementing features or fixes in the `dev` branch.
        validations:
          required: true
      - type: textarea
        id: step-2
        attributes:
          label: Step 2: Fork Current Repository and Complete Task 1 and 2
          description: |
            - **Objective:** Fork the repository, update the `dev` branch, and create a personal feature branch.

            **Steps:**

            1. **Fork the Repository:**
               - Go to the GitHub repository and click the "Fork" button in the top-right corner.

            2. **Clone Your Fork:**
               - Clone your forked repository to your local machine:
                 ```
                 git clone git@github.com:[Your GitHub Username]/Recall-Analysis-WebApp.git
                 cd Recall-Analysis-WebApp
                 ```

            3. **Add Upstream Remote:**
               - Add the original repository as an upstream remote:
                 ```
                 git remote add upstream git@github.com:sys-hackathon/Recall-Analysis-WebApp.git
                 ```

            4. **Complete Task 1: Update `dev` Branch and Propose Changes**

               - **Objective:** Update the pre-existing `dev` branch with the latest changes from `main` and propose improvements or fixes.

               **Steps:**

               1. **Fetch and Merge:**
                  ```
                  git fetch origin
                  git checkout dev
                  git merge origin/main
                  ```

               2. **Make Changes:**
                  - Implement any necessary changes or improvements in the `dev` branch.

               3. **Commit Changes:**
                  ```
                  git commit -m "Update: [Brief description of changes]"
                  ```

               4. **Push Changes:**
                  ```
                  git push origin dev
                  ```

               5. **Create a Pull Request:**
                  - Go to the GitHub repository and create a pull request from `dev` to `main`.

            5. **Complete Task 2: Create Own Branch with Good Naming Convention**

               - **Objective:** Create a new branch for personal development work following a good naming convention.

               **Steps:**

               1. **Create Branch:**
                  ```
                  git checkout -b feature/[your-initials]-[brief-description]
                  ```
                  Example: `feature/jd-add-user-authentication`

               2. **Work on Your Feature:**
                  - Implement your feature or fix in this new branch.

               3. **Commit Changes:**
                  ```
                  git commit -m "Add: [Brief description of feature or fix]"
                  ```

               4. **Push Branch:**
                  ```
                  git push -u origin feature/[your-branch-name]
                  ```
        validations:
          required: true
      - type: input
        id: github-username
        attributes:
          label: GitHub Username
          description: Please provide your GitHub username.
        validations:
          required: true
      - type: textarea
        id: questions-or-concerns
        attributes:
          label: Any Questions or Concerns
          description: Please write any questions or concerns here.
